### PR TITLE
Visual Game Map

### PR DESCRIPTION
**Pull request by miketwo**
### What
Completely redone game map code. 

### Features

- Supports multiple paths and player choice after each encounter. 
- Highlights the current node with `--> NAME <--`. 
- Tests covering basic map generation and iteration.

### Caveats
 - Can't get colored ASCII to work :(
 - The code is complicated. It's surprisingly hard to automatically generate a graph in ASCII. We may want to consider simpler alternatives that don't allow as much dynamic generation. (i.e. hard-coded maps that don't change.)

### To Use/Test
Play the game and see!

For details, see `create_first_map()` for an example of how to create a map. 

### Example output

```
                            +------+                             
                          **| BOSS |***                          
                      ****  +------+*  ****                      
                 *****     *         *     *****                 
             ****        **           **        ****             
          ***           *               *           ***          
+--------+        +--------+        +--------+        +--------+ 
| NORMAL |        | NORMAL |        | NORMAL |        | NORMAL | 
+--------+        +--------+        +--------+        +--------+ 
         *         *                         *         *         
          **     **                           **     **          
            *   *                               *   *            
          +-------+                           +-------+          
          | ELITE |***                     ***| ELITE |          
          +-------+   ******        *******   +-------+          
              *             ********              *              
              *        *******     ******         *              
              *    ****                  ****     *              
        +---------+                         +-----------+        
        | UNKNOWN |                         | REST_SITE |        
        +---------+                         +-----------+        
         *         *                         *         *         
       **           **                     **           **       
      *               *                   *               *      
+--------+        +--------+        +--------+        +--------+ 
| NORMAL |***     | NORMAL |        | NORMAL |      **| NORMAL | 
+--------+   **** +--------+        +--------+  ****  +--------+ 
                 *****     *         *     *****                 
                      ****  **     **  ****                      
                          *** *   * ***                          
                        +---------------+                        
                        | --> START <-- |                        
                        +---------------+   
```

### CODE REVIEW

**Review by Vesper-arch — APPROVED** [review]
Wow, tbh I wasn't even thinking of doing this because it's really complex and I don't understand it.

**Comment by Vesper-arch** [comment]
> ### Caveats
> * Can't get colored ASCII to work :(
> * The code is complicated. It's surprisingly hard to automatically generate a graph in ASCII. We may want to consider simpler alternatives that don't allow as much dynamic generation. (i.e. hard-coded maps that don't change.)

Could the maps be hard coded and stored in some kind of data file? Plus the names could be pre-parsed so they can just be inserted into the map display. Idk man, this is just an idea I came up with after looking through the pr description.

**Comment by miketwo** [comment]
Yeah with hardcoded maps we can make it look better. You just draw the map(s) in ASCII and then have a simple data structure (like a linked list or dictionary) for player choices. That's a lot easier, but changing the map becomes much harder, cause you have to manually redraw everything.

**Comment by Vesper-arch** [comment]
When would the map have to be redrawn?

**Comment by miketwo** [comment]
Anytime we'd want to change the order of things.

I'll take a second look at the colored ASCII. It might be possible. The main problem was getting everything to line up after putting in the color control characters. But I have an idea about doing a second pass for coloring.

**Comment by Vesper-arch** [comment]
This is what I think could work as a map structure:
```python
test_map = [
    [None, None, ("Rest Site", ["14d"]), ("Rest Site", ["14d"]), ("Rest Site", ["14d"]), None, ("Rest Site", ["14g"])],
    [None, None, None, ("Monster", ["13c", "13d"]), None, ("Unknown", ["13g"]), ("Monster", ["13g"])],
    [None, None, ("Unknown", ["12b"]), ("Merchant", ["12c", "12d"]), None, None, ("Monster", ["12g"])],
    [None, ("Rest Site", ["11b"]), ("Monster", ["11c"]), ("Monster", ["11e"]), None, None, ("Rest Site", ["11f", "11g"])],
    [None, ("Elite", ["10b"]), ("Unknown", ["10b", "10c"]), None, ("Unknown", ["10f"]), ("Monster", ["10g"]), ("Unknown", ["10g"])],
    [None, ("Unknown", ["9a", "9b"]), ("Monster", ["9d"]), None, None, ("Monster", ["9f"]), ("Elite", ["9f"])],
    [("Treasure", ["8a"]), ("Treasure", ["8a"]), None, ("Treasure", ["8d"]), None, ("Treasure", ["8e", "8f", "8g"]), None],
    [("Unknown", ["7a"]), None, None, ("Rest Site", ["7e"]), ("Elite", ["7f"]), ("Monster", ["7f"]), ("Unknown", ["7g"])],
    [("Monster", ["6a", "6b"]), None, None, None, ("Monster", ["6d"]), ("Unknown", ["6e", "6f"]), ("Elite", ["6g"])],
    [("Rest Site", ["5b"]), ("Monster", ["5b"]), None, ("Monster", ["5c"]), ("Monster", ["5d"]), ("Unknown", ["5e"]), ("Rest Site", ["5g"])],
    [None, ("Unknown", ["4b", "4c"]), ("Monster", ["4c"]), ("Merchant", ["4c"]), ("Monster", ["4d"]), None, ("Merchant", ["4f"])],
    [None, ("Unknown", ["3b"]), ("Monster", ["3b", "3c"]), ("Monster", ["3d"]), None, ("Unknown", ["3e"]), None],
    [None, ("Merchant", ["2a", "2b"]), ("Monster", ["2b"]), ("Monster", ["2e"]), ("Unknown", ["2f"]), (), ()],
    [("Unknown", ["1a"]), ("Monster", ["1b"]), None, None, ("Unknown", ["1d"]), ("Monster", ["1e"]), None] # This is floor 2. Floor 1 is added after.
]
```
Map this corresponds to:
2830078257_preview_M7

**Comment by Vesper-arch** [comment]
Looks horrendous but it may work.

**Pull request merged**
