### PR TITLE
Not meant to be merged -- Example Message Bus

### PR DESCRIPTION
**Pull request by miketwo**
## What is this?
This is an example of using a **message bus** to handle combat.

## Why?
To isolate logic and make everything more testable. 

So, instead of something like this, where all the game logic is mixed:
```python
if relics['Strike Dummy'] in self.relics and 'strike' in card.get('Name').lower():
    ...
if self.debuffs["Weak"] > 0 and card:
    ...
if target.debuffs["Vulnerable"] > 0:
    ...
if self.buffs["Vigor"] > 0:
    ...
```

We have something like this:
```python
self.bus.publish(Message.START_OF_COMBAT, self)
self.bus.publish(Message.START_OF_TURN, self)
...
self.bus.publish(Message.BEFORE_ATTACK, (origin, target, card))
...
self.bus.publish(Message.AFTER_ATTACK, (origin, target, card))
...
self.bus.publish(Message.END_OF_TURN, self)
```

These lines emit messages during different parts of combat, and players/buffs/debuffs/relics respond and
modify game state appropriately.

If done right, you should rarely have to modify the combat logic. Just add more cards, buffs and relics and what they react to, and they'll Just Work™.

## Ok, so what's in the example?
This example shows a 1vs1 combat with 2 identical attacks across 2 turns. To run it, just do:

```bash
python example_message_bus_game_engine.py
```

Damage is calculated and modified by buffs/debuffs/relics, which differ from the first attack to the second. To keep it short, many things are simplified/ignored (no energy, blocking, discard pile, user choice, etc...).

The most important aspect to notice is that all the buffs/debuffs/relics logic is completely isolated from each other and from the combat. This allows for independent coding and testing -- you can stand up a test where you send it certain messages and verify that it modifies the game state correctly.

Apologies for the long example. Just something to consider. It's a more advanced way of coding the game engine, but it's also less likely to have regressions (where you fix one thing and it breaks another). Hopefully it makes sense.

## Expected Output

This, but with colors:
```bash
$ python example_message_bus_game_engine.py 

Turn 1
Player : 100hp | Buffs: ['Strength'] | Debuffs: [] | Relics: ['Akabeko']
Enemy  : 100hp | Buffs: [] | Debuffs: ['Vulnerable'] | Relics: []

Enemy took 24 damage from Strike(+6 dmg) | Strength(+2 dmg) | Akabeko(+8 dmg) | Vulnerable(+8 dmg)
Player: Strength wore off.

Turn 2
Player : 100hp | Buffs: [] | Debuffs: [] | Relics: ['Akabeko']
Enemy  :  76hp | Buffs: [] | Debuffs: ['Vulnerable'] | Relics: []

Enemy took 9 damage from Strike(+6 dmg) | Vulnerable(+3 dmg)

Turn 2
Player : 100hp | Buffs: [] | Debuffs: [] | Relics: ['Akabeko']
Enemy  :  67hp | Buffs: [] | Debuffs: ['Vulnerable'] | Relics: []
```

### CODE REVIEW

**Comment by Vesper-arch** [comment]
A few comments:

- Debuff/Buffs are ticked down at the start of the player's turn, I am not sure if the `fresh_effects` system would work with that though.
- the Akabeko relic, contrary to its description making it seem like a special effect, applies the buff Vigor. Vigor increases the damage of the next attack by X. Same effect though.
- Buffs that have the Intensity stack type(detailed by the [wiki](https://docs.google.com/document/d/1j7c3oHXeQjjF6yyuY0tOMaZeMlAHPokfzw99Azpe6fk/edit?usp=sharing)) either wear off completely at the start of their turn or persist for the entire combat encounter.

**Comment by Vesper-arch** [comment]
Also, is there a way I can merge just the dependencies commit?

**Comment by Vesper-arch** [comment]
I am not sure I completely understand the moment-to-moment process of the system. Is it like each class sends something to be printed at a certain point based on some condition or what?

**Comment by miketwo** [comment]
Try turning `debug=True` on line 225 on the MessageBus -- it'll show all the messages. 

I can talk through the first bit. As all the objects are created or given to the player/enemy, they get registered. So you'll see output like this:
```
MESSAGEBUS: before_attack | Subscribed Buff_Strength.callback
MESSAGEBUS: end_of_turn | Subscribed Buff_Strength.callback
MESSAGEBUS: start_of_combat | Subscribed Relic_Akabeko.callback
MESSAGEBUS: before_attack | Subscribed Relic_Akabeko.callback
MESSAGEBUS: after_attack | Subscribed Relic_Akabeko.callback
MESSAGEBUS: end_of_turn | Subscribed Character.callback
MESSAGEBUS: before_attack | Subscribed Debuff_Vulnerable.callback
MESSAGEBUS: end_of_turn | Subscribed Debuff_Vulnerable.callback
MESSAGEBUS: end_of_turn | Subscribed Character.callback
```

For each type of message, a callback function is saved. When the message bus gets that message, it's going to call the callback functions of everyone that subscribed.

So, for example, the very first part of the demo:
```python
self.bus.publish(Message.START_OF_COMBAT, self)
```
That first line broadcasts a `START_OF_COMBAT` message. In the demo, the only thing that's subscribed to this message is the Akabeko relic. So the message bus calls `Akabeko.callback(...)`, and this code runs:
```python
def callback(self, message, context):
      if message == Message.START_OF_COMBAT:
        self.first_attack = True
      if message == Message.BEFORE_ATTACK and self.first_attack:
          ...
```
The Akabeko object checks the message type, and because it's `START_OF_COMBAT`, it resets itself (`self.first_attack = True`). 

There's no one else subscribed to `START_OF_COMBAT`, so it goes back to the demo code:
```python
self.bus.publish(Message.START_OF_TURN, self)
```
This broadcasts a `START_OF_TURN`, but since no one is subscribed to it, nothing happens. (But you could use this to tick the buffs, for example.)

Next line in demo():
```python
self.play_card(...)
```
jumps to the `play_card()` function:
```python
        self.bus.publish(Message.BEFORE_ATTACK, (origin, target, card))    <------ we are here
        card.apply(target)
        self.bus.publish(Message.AFTER_ATTACK, (origin, target, card))
```
That first line emits a `BEFORE_ATTACK` message. A bunch of things are subscribed to this, so they run one after the other. First is `Buff_Strength.callback`:
```python
        if message == Message.END_OF_TURN:
            self.duration -= 1
        if message == Message.BEFORE_ATTACK and self.duration > 0:
            origin, target, card = context
            dmg_affected_by = "<buff>Strength</buff>"
            card.modify_damage(self.amount, reason=dmg_affected_by)
```
So this checks that it's duration is positive, and then it **modifies the damage that the card will apply** (that last line). 

Then the `Relic_Akabeko.callback()` runs, and it does the same thing.
Then the `Debuff_Vulnerable.callback()` runs, and it does the same thing. 

See how it works?

**Comment by Vesper-arch** [comment]
That's genius. I never would have thought of that. I still don't get how to run it myself though, still new to github's pr system

**Comment by miketwo** [comment]
Hmm.. well it's safe to merge. It'll just be an extra file you can delete later. But in a dev environment you would do `git checkout example_message_bus` to switch to the branch that has the code. From there you can run it or test it or whatever. And then `git checkout main` to get back. 

It's good to learn the command-line version of things, because then you can move from system to system. Like, I have no idea how Replit does git stuff, but I'd know I need to look for a checkout option if I wanted to check out different branches, or a "remote" option if I wanted to check out different repos. Once you learn it raw, then whatever buttons and UI people put on it, you'll be able to figure it out.

**Review by Vesper-arch — APPROVED** [review]

**Comment by Vesper-arch** [comment]
I almost want to rewrite the game using this to see how much easier it would be.

**Comment by miketwo** [comment]
Yeah, if you want. It's also not too bad to migrate it. Just hook up the bus and start posting messages at different points in the code. Then migrate the relics one by one. You might also want a way to log what's going on to a file (so that you can log debugging stuff without interfering with the user's display).

**Comment by Vesper-arch** [comment]
What does the `dataclass` decorator do? Do I even need it?

**Comment by miketwo** [comment]
`dataclass` is shorthand for creating classes with a built-in `__init__()`, `__repr__()`, and other methods. You don't need it, but you'd have to supply the init method, otherwise the line `game = Combat(player=player, enemy=enemy, bus=bus)` wouldn't work. 

UID is for de-duplication. You (usually) don't want things that register with a bus to be called multiple times, so that makes it so the bus can decide what to do in that circumstance. 

Example: consider the following situation *without UIDs*:

```python
message_bus.subscribe("event", enemy.first_function)           
#...lots of code
message_bus.subscribe("event", enemy.second_function)          
#...lots of code
message_bus.publish("event", data)                      
```

Should it call both functions? Just the first? Just the second? Any answer is ok, so long as it's consistent. If it's going to be either function (but not both), then you'll need a UID to distinguish them. 

Personally, I prefer that it only make 1 call per UID, and that the call is the last one to register (`second_function`). I just think it's easier, but however you want to do it works -- we'll just need to pick something and stick to it.

**Comment by Vesper-arch** [comment]
I was so scared for a second, I thought you deleted the branch I was working on. I'll look into using UIDs later today.

**Pull request merged**
