### PR TITLE
Message Bus Engine v1

### PR DESCRIPTION
**Pull request by Vesper-arch**

### CODE REVIEW

**Comment by Vesper-arch** [comment]
I am scared to resolve those conflicts because of what happened last time.

**Comment by Vesper-arch** [comment]
@miketwo How would I go about resolving the merge conflicts? Last time I had to create a sort of combination between the 2. That apparently messed up a lot of stuff as you saw when I tried to update the message bus branch with commits from main.

**Comment by miketwo** [comment]
Yeah merge conflicts suck, hah. I'll show you how I would do it.

In this case, you have only 1 commit on `message_bus_engine`, so a `git rebase` will do the trick. Rebase re-applies all the commits on a branch to a different starting point. We want to rebase onto main, so at the end it'll look like just 1 commit "on top" of main. Here's a picture (you can get this with the command `gitk --all`)

image

So from the `message_bus_engine` branch, you would do `git rebase origin/main` (assuming yours is called origin -- mine is called 'upstream' because I forked your code.)

That makes the conflicts appear in VSCode. You can edit the files to resolve the conflicts -- the "broken" files will be red. Here's a gif showing a bit of what that looks like:

example1

Once it's all cleaned up (and tests pass!), you do 2 commands:

- `git add -A` (marks all broken files as resolved)
- `git rebase --continue` (finishes the rebase)

Now you can update GitHub's copy of the branch by force pushing: `git push origin message_bus_engine:message_bus_engine --force`.

(Heads up that you almost never want to force push. One person force pushing breaks all other people's `git pull` on the branch that was pushed. This is a special case because there's only 2 people working on it and I know how to fix it on my end when `git pull` breaks.) 

If you wanted to do it the more traditional way, it's almost the same. You do:
-  `git merge main` in place of `git rebase main`, 
-  resolve all conflicts and `git add` them to mark resolved
-  `git merge --continue`
- REGULAR (not force) push: `git push origin message_bus_engine`

**Comment by miketwo** [comment]
Also heads up that you want to find and remove `pytest.mark.only` so that all the tests run.

**Comment by miketwo** [comment]
And, generally-speaking, you probably want to accept the "INCOMING" changes, as those will correspond to your current branch. (It's weird and backwards-sounding).

**Comment by Vesper-arch** [comment]
I think I get it but I don't understand the `gitk --all` output. I'm just not sure how it displays the info or what logic it has.

**Comment by miketwo** [comment]
It's a visual representation of branches. Each dot is a commit. The yellow dot is the current commit. The lines show how the commits are connects. (Branches are "splits" and merges are "combines"). When your done with the rebase, it should look something like this:
image

Just one commit on top of main.

**Comment by miketwo** [comment]
Let me know if you need help and I can resolve the conflicts for you. (Adding a message bus is hard enough without having to fight with git.)

**Comment by Vesper-arch** [comment]
Got it!

**Comment by Vesper-arch** [comment]
GitHub doesn't think so, I guess.

**Comment by Vesper-arch** [comment]
I did the push command but git hub shows that its even more offset from main than before

**Comment by miketwo** [comment]
Your local main is not up to date. That's why it's good to specify the Github's main ("origin"):

>So from the message_bus_engine branch, you would do `git rebase origin/main` (assuming yours is called origin -- mine is called 'upstream' because I forked your code.)

On your main branch, you need to git pull. And now you've got a whole boatload of repeated commits to fix. Let me see if I can help...

**Comment by Vesper-arch** [comment]
I did `git pull` on both `main` and `message_bus_engine` and they both said that it was already up to date. Its only when I do `git rebase origin/main` on the message bus branch does it show those commits and the conflicts of course

**Comment by miketwo** [comment]
Hmm... That's strange. Ok. So where is the commit where you fixed all the conflicts? (Did you go through the broken files fixing them?) There's no way around that part of it.

**Comment by miketwo** [comment]
Ok. I pushed a branch (`message_bus_fixed`) that's just 1 commit on top of main, and is identical to the `message_bus_engine` branch. Feel free to switch to that branch if you want to avoid the conflicts.

**Comment by Vesper-arch** [comment]
> Hmm... That's strange. Ok. So where is the commit where you fixed all the conflicts? (Did you go through the broken files fixing them?) There's no way around that part of it.

It should show as that group of 17 commits above. I did go through the rebasing for each of them.

**Comment by Vesper-arch** [comment]
Ok, I'm going to delete this one and make a new draft from the fixed branch. Thank you!

**Pull request closed without merging**
