### PR TITLE
Update message_bus_engine

### PR DESCRIPTION
**Pull request by Vesper-arch**

### CODE REVIEW

**Comment by Vesper-arch** [comment]
why did it commit to main

**Comment by Vesper-arch** [comment]
@miketwo How do I undo that last commit? I only wanted to update the `message_bus_engine` branch to where `main` was, but it also committed to main.

**Comment by miketwo** [comment]
This looks all kinds of jacked. It's treating your main branch as the PR branch and vice-versa. 

I would suggest:

- Reverting the commit on main and pushing.
- Closing this PR.
- Updating the message_bus_engine branch and pushing

If you push the very latest changes you have, I can fix do the rest. But you'll lose anything local that isn't pushed.

**Comment by Vesper-arch** [comment]
I really don't know what happened there. I'm gonna undo the commit and the close the PR. The message bus still isn't working so I'll hold off on pushing it.

**Comment by miketwo** [comment]
It's ok to push things that aren't complete. (There's a difference between pushing and merging). Pushing a branch just puts a copy on GitHub -- it could be completely broken, but it lets others look at the code and make comments. For example, I just pushed `shop_v2` [and made a draft PR here](https://github.com/Vesper-arch/Slay-The-Spire-in-Python/pull/57). I'll keep pushing changes as I work on that, and you'll be able to comment on it as it goes. But we don't have to merge it into main until it's done. 

So, same deal, you could have a `message_bus_engine` branch that you keep pushing to, so your work is backed up and so I can help/make comments.

**Pull request closed without merging**
